[greeter]
background=/usr/share/fennec/branding/fennec-login.png
user-background=false
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=Sans 10
xft-antialias=true
xft-hintstyle=hintfull
xft-rgba=rgb
