[*]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=/usr/share/fennec/branding/fennec-wallpaper.png

desktop_bg=#000000
desktop_fg=#111111
desktop_shadow=#f0d9a0

show_wm_menu=0
show_documents=0
show_trash=1
show_mounts=1

sort=mtime;ascending;
