---
dontChroot: true
timeout: 30

script:
  - "/bin/rm -f ${ROOT}/etc/resolv.conf.calamares-fennec"
  - "/bin/cp -a ${ROOT}/etc/resolv.conf ${ROOT}/etc/resolv.conf.calamares-fennec"
  - "/bin/rm -f ${ROOT}/etc/resolv.conf"
  - "/bin/cp -L /etc/resolv.conf ${ROOT}/etc/resolv.conf"
